### ISSUE TITLE
Assignment problem: "warped_masked_mel_spectrogram = warped_mel_spectrogram"

### ISSUE THREAD

**Issue by luan78zaoha** [shelling203/SpecAugment#1]
Assignment problem:
https://github.com/shelling203/SpecAugment/blob/7a4a2789e4cee54673de687e2faae57571195735/SpecAugment/spec_augment.py#L79

Here is the "shallow copy". So, it could be modified as "warped_masked_mel_spectrogram = warped_mel_spectrogram.copy()"

**Comment by DemisEom** [comment]
thank you for your opinion.
this line was test code used for compare warping and masking.
So, this line is deleted now.
