### ISSUE TITLE
About the magic numbers in time warp

### ISSUE THREAD

**Issue by Hu-Wenchao** [shelling203/SpecAugment#2]
# Image warping control point setting
    control_point_locations = np.asarray([[64, 64], [64, 80]])
    control_point_locations = constant_op.constant(
        np.float32(np.expand_dims(control_point_locations, 0)))

    control_point_displacements = np.ones(
        control_point_locations.shape.as_list())
    control_point_displacements = constant_op.constant(
        np.float32(control_point_displacements))

    # mel spectrogram data type convert to tensor constant for sparse_image_warp
    mel_spectrogram = mel_spectrogram.reshape([1, mel_spectrogram.shape[0], mel_spectrogram.shape[1], 1])
    mel_spectrogram_op = constant_op.constant(np.float32(mel_spectrogram))
    w = random.randint(0, time_warping_para)

Hi, in your implementation, random value w is not used and you put several magic number ([[64, 64], [64, 80]]) here, it is not same as what depicted in the paper, can you tell why you do this?

**Comment by DemisEom** [comment]
yes, not now don't use random value w, that part is now implementing. 
magic number is testing value for understanding how to work 'image_warp' function.
near future, will be implemented using random value w.
thank you.
