### ISSUE TITLE
getting slower each time i call

### ISSUE THREAD

**Issue by boji123** [shelling203/SpecAugment#3]
There is a tensorflow operation in your code (in line 86) and it will add a new graph each time i call it, making tf operations more and more slowly.
Try to use feed dict to fix this problem. 
Your appreciate.

SpecAugment/SpecAugment/spec_augment_tensorflow.py:86
`control_point_locations = constant_op.constant(
        np.float32(np.expand_dims(control_point_locations, 0)))`

**Comment by DemisEom** [comment]
Thank you for your good advice.
I am aware of this problem and am implementing "sparse_image_warp" not depend on tensorflow.
We will release it soon after its implementation.
Thank you.

**Comment by DemisEom** [comment]
now feed_dict version updated

**Comment by wuyilengbi** [comment]
I tried the code , the problem that  it is more amd more slowly.

how to fix it?

**Comment by vietanh125** [comment]
I have found a workaround. You need to move all placeholders as well as the session out of the spec_augment function and then add `sess.run(tf.global_variables_initializer())`. It should run super fast!

**Comment by asjiangh** [comment]
> I have found a workaround. You need to move all placeholders and session outside the function and add `sess.run(tf.global_variables_initializer())`. It should run super fast!

Hello! 
Could you share your code? I have the same problem and I'm not quite sure your meaning.
Thanks!
