### ISSUE TITLE
Please add tensorflow-gpu to requirements.

### ISSUE THREAD

**Issue by ZhaoZeyu1995** [shelling203/SpecAugment#4]
When I use `pip install SpecAugment` it will install tensorflow==1.13.1, but I’ve already had tensorflow-gpu==1.13.1 installed. I hope this can be fixed ASAP.

**Comment by DemisEom** [comment]
Thank you for your interest.
I uploaded a package that changed the requirement package list.
you can install new version package by "pip install SpecAugment==1.2.4"
Thank you.
